<!-- Message de notification -->

<!-- Code HTML à écrire -->


<!-- Liste des aliments -->
<table class="generic-table meal-list table">
    <caption>Carte du restaurant</caption>
    
    <tbody>
        <!-- Code HTML à écrire <-->
        <?php foreach($meals as $meal){ ?>
            <tr>
                <td>
                    <img src="<?= $wwwUrl ?>/images/meals/<?= $meal['Photo'] ; ?>" class="mealimg" alt="">                
               </td>
                <td>
                    <p><strong><?= $meal['Name'] ; ?></strong></p>
                
                    <?= $meal['Description'] ; ?>
                </td>
                <td>
                   <strong><?= $meal['SalePrice'] ; ?> €</strong> 
                </td>
                
            </tr>
        <?php } ?>
    </tbody>
</table>