<h2><i class="fa fa-user"></i> Ajouter meal</h2>

<div class="container">
        <form class="generic-form" action="<?= $requestUrl ?>/meal"  method="POST" enctype="multipart/form-data">
			
			<fieldset>
				
                <label for="nom">Nom :</label>
                <input id="nom" type="text" name="nom" class="form-control">

                <label for="desc">Description :</label>
                <textarea name="desc" id="desc" cols="30" rows="10"class="form-control"></textarea>
                
                <label for="photo">Image</label>
                <input type="file" name="photo" class="form-control">

                <label for="quant">Quantité en Stock</label>
                <input type="number" name="quantity" class="form-control">
                
                <label for="buy">Prix d'achat</label>
                <input type="text" name="buyprix" class="form-control">
                
                <label for="sale">Prix de vente</label>
                <input type="text" name="saleprix" class="form-control">
						
	</fieldset>
	
			<input class="btn btn-success" type="submit" value="Ajouter un meal" >
			<a class="btn btn-danger small" href="<?= $requestUrl ?>">Annuler</a>
		
		</form>
</div>